insert into student
values(10001,'Ranga', 'E1234567');

insert into student
values(10002,'Ravi', 'A1234568');


insert into parking values(1, 4);
insert into parking values(2, 3);
insert into parking values(3, 2);
insert into parking values(4, 10);

//insert into parking_bay (index, pedestrianExit, disabledBay, occupied, id) values (301, false, false, false, 1);
//insert into parking_bay values(302, false, false, false, 1);
//insert into parking_bay values(303, false, false, false, 1);
//insert into parking_bay values(304, false, false, false, 1);
//insert into parking_bay values(305, false, false, false, 1);
//insert into parking_bay values(306, false, false, false, 1);
//insert into parking_bay values(307, false, false, false, 1);
//insert into parking_bay values(308, false, false, false, 1);
//insert into parking_bay values(309, false, false, false, 1);
//insert into parking_bay values(310, false, false, false, 1);
//insert into parking_bay values(311, false, false, false, 1);
//insert into parking_bay values(312, false, false, false, 1);
//insert into parking_bay values(313, false, false, false, 1);
//insert into parking_bay values(314, false, false, false, 1);
//insert into parking_bay values(315, false, false, false, 1);
//insert into parking_bay values(316, false, false, false, 1);
//
//
//insert into parking_bay values(201, false, false, false, 2);
//insert into parking_bay values(202, true, false, false, 2);
//insert into parking_bay values(203, false, false, false, 2);
//insert into parking_bay values(204, true, false, false, 2);
//insert into parking_bay values(206, true, false, false, 2);
//insert into parking_bay values(207, false, false, false, 2);
//insert into parking_bay values(208, true, false, false, 2);
//insert into parking_bay values(209, false, false, false, 2);


//insert into parking_bay (index, pedestrian_exit, disabled_bay, occupied, type_bay, min_distance, id) values(101, false, false, '', 'NON_DISABLED_EMPTY', null, 3);
//insert into parking_bay (index, pedestrian_exit, disabled_bay, occupied, type_bay, min_distance, id) values(102, false, true, '', 'DISABLED_EMPTY', null, 3);
//insert into parking_bay (index, pedestrian_exit, disabled_bay, occupied, type_bay, min_distance, id) values(103, false, false, '', 'NON_DISABLED_EMPTY', null, 3);
//insert into parking_bay (index, pedestrian_exit, disabled_bay, occupied, type_bay, min_distance, id) values(104, false, false, '', 'NON_DISABLED_EMPTY', null, 3);

insert into parking_bay (index, pedestrian_exit, disabled_bay, occupied, min_distance, id) values(101, false, false, 'U',  null, 3);
insert into parking_bay (index, pedestrian_exit, disabled_bay, occupied, min_distance, id) values(102, false, true, '@',  null, 3);
insert into parking_bay (index, pedestrian_exit, disabled_bay, occupied, min_distance, id) values(103, false, false, 'U',  null, 3);
insert into parking_bay (index, pedestrian_exit, disabled_bay, occupied, min_distance, id) values(104, false, false, 'U',  null, 3);

//insert into parking_bay values(1, false, false, false, 4);
//insert into parking_bay values(2, false, true, false, 4);
//insert into parking_bay values(3, false, false, false, 4);
//insert into parking_bay values(4, false, false, false, 4);
//insert into parking_bay values(5, false, false, false, 4);
//insert into parking_bay values(6, false, false, false, 4);
//insert into parking_bay values(7, false, false, false, 4);
//insert into parking_bay values(9, false, false, false, 4);
//insert into parking_bay values(10, false, false, false, 4);
//insert into parking_bay values(11, false, false, false, 4);
//insert into parking_bay values(12, false, false, false, 4);
//insert into parking_bay values(13, false, false, false, 4);
//insert into parking_bay values(14, false, false, false, 4);
//insert into parking_bay values(15, false, false, false, 4);
//insert into parking_bay values(16, false, false, false, 4);
//insert into parking_bay values(17, false, false, false, 4);
//insert into parking_bay values(18, false, false, false, 4);
//insert into parking_bay values(19, false, false, false, 4);
//insert into parking_bay values(20, false, false, false, 4);
//insert into parking_bay values(21, false, false, false, 4);
//insert into parking_bay values(22, false, false, false, 4);
//insert into parking_bay values(23, false, false, false, 4);
//insert into parking_bay values(24, false, false, false, 4);
//insert into parking_bay values(25, false, false, false, 4);
//insert into parking_bay values(26, false, false, false, 4);
//insert into parking_bay values(27, false, false, false, 4);
//insert into parking_bay values(28, false, false, false, 4);
//insert into parking_bay values(29, false, false, false, 4);
//insert into parking_bay values(30, false, false, false, 4);
//insert into parking_bay values(31, false, false, false, 4);
//insert into parking_bay values(32, false, false, false, 4);
//insert into parking_bay values(33, false, false, false, 4);
//insert into parking_bay values(34, false, false, false, 4);
//insert into parking_bay values(35, false, false, false, 4);
//insert into parking_bay values(36, false, false, false, 4);
//insert into parking_bay values(37, false, false, false, 4);
//insert into parking_bay values(38, false, false, false, 4);
//insert into parking_bay values(39, false, false, false, 4);
//insert into parking_bay values(40, false, false, false, 4);
//insert into parking_bay values(41, false, false, false, 4);
//insert into parking_bay values(43, false, false, false, 4);
//insert into parking_bay values(44, false, false, false, 4);
//insert into parking_bay values(45, false, false, false, 4);
//insert into parking_bay values(46, false, false, false, 4);
//insert into parking_bay values(47, false, true, false, 4);
//insert into parking_bay values(48, false, false, false, 4);
//insert into parking_bay values(49, false, false, false, 4);
//insert into parking_bay values(50, false, false, false, 4);
//insert into parking_bay values(51, false, false, false, 4);
//insert into parking_bay values(52, false, false, false, 4);
//insert into parking_bay values(53, false, false, false, 4);
//insert into parking_bay values(54, false, false, false, 4);
//insert into parking_bay values(55, false, false, false, 4);
//insert into parking_bay values(56, false, false, false, 4);
//insert into parking_bay values(57, false, false, false, 4);
//insert into parking_bay values(58, false, false, false, 4);
//insert into parking_bay values(59, false, false, false, 4);
//insert into parking_bay values(60, false, false, false, 4);
//insert into parking_bay values(61, false, false, false, 4);
//insert into parking_bay values(62, false, false, false, 4);
//insert into parking_bay values(63, false, false, false, 4);
//insert into parking_bay values(64, false, false, false, 4);
//insert into parking_bay values(65, false, false, false, 4);
//insert into parking_bay values(66, false, false, false, 4);
//insert into parking_bay values(67, false, false, false, 4);
//insert into parking_bay values(68, false, false, false, 4);
//insert into parking_bay values(69, false, false, false, 4);
//insert into parking_bay values(70, false, false, false, 4);
//insert into parking_bay values(71, false, false, false, 4);
//insert into parking_bay values(72, false, true, false, 4);
//insert into parking_bay values(73, false, false, false, 4);
//insert into parking_bay values(74, false, false, false, 4);
//insert into parking_bay values(75, false, false, false, 4);
//insert into parking_bay values(76, false, false, false, 4);
//insert into parking_bay values(77, false, false, false, 4);
//insert into parking_bay values(78, false, false, false, 4);
//insert into parking_bay values(79, false, false, false, 4);
//insert into parking_bay values(80, false, false, false, 4);
//insert into parking_bay values(81, false, false, false, 4);
//insert into parking_bay values(82, false, false, false, 4);
//insert into parking_bay values(83, false, false, false, 4);
//insert into parking_bay values(84, false, false, false, 4);
//insert into parking_bay values(86, false, false, false, 4);
//insert into parking_bay values(87, false, false, false, 4);
//insert into parking_bay values(88, false, false, false, 4);
//insert into parking_bay values(89, false, false, false, 4);
//insert into parking_bay values(90, false, false, false, 4);
//insert into parking_bay values(91, false, false, false, 4);
//insert into parking_bay values(92, false, false, false, 4);
//insert into parking_bay values(93, false, false, false, 4);
//insert into parking_bay values(94, false, false, false, 4);
//insert into parking_bay values(95, false, false, false, 4);
//insert into parking_bay values(96, false, false, false, 4);
//insert into parking_bay values(97, false, false, false, 4);
//insert into parking_bay values(98, false, false, false, 4);
//insert into parking_bay values(99, false, false, false, 4);
//insert into parking_bay values(100, false, false, false, 4);